from fpdf import FPDF
from datetime import datetime


class AutoFixReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(88, 166, 255)
        self.cell(0, 10, "AutoFix AI - Code Analysis Report", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_draw_color(48, 54, 61)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(139, 148, 158)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Generated by AutoFix AI", align="C")


def generate_pdf_report(result: dict) -> bytes:
    pdf = AutoFixReport()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # --- File Info ---
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(225, 228, 232)
    pdf.cell(0, 8, f"File: {result['original_file']}", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(139, 148, 158)
    language = result.get("language", "python")
    pdf.cell(0, 6, f"Language: {language.capitalize()} | Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # --- Summary ---
    summary = result["summary"]
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(88, 166, 255)
    pdf.cell(0, 10, "Summary", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 11)
    col_width = 45
    row_height = 8

    # Table header
    pdf.set_fill_color(33, 38, 45)
    pdf.set_text_color(225, 228, 232)
    for header in ["Bugs", "Security", "Style", "Total"]:
        pdf.cell(col_width, row_height, header, border=1, fill=True, align="C")
    pdf.ln()

    # Table row
    colors = {
        "bugs": (248, 81, 73),
        "security": (210, 153, 34),
        "style": (88, 166, 255),
        "total": (225, 228, 232),
    }
    for key in ["bugs", "security", "style", "total"]:
        r, g, b = colors[key]
        pdf.set_text_color(r, g, b)
        pdf.cell(col_width, row_height, str(summary.get(key, 0)), border=1, align="C")
    pdf.ln(12)

    # --- Issues ---
    issues = result.get("issues", [])
    if issues:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(88, 166, 255)
        pdf.cell(0, 10, f"Issues Found ({len(issues)})", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        for i, issue in enumerate(issues, 1):
            issue_type = issue.get("type", "bug")
            severity = issue.get("severity", "info")
            line = issue.get("line", "?")
            desc = issue.get("description", "")
            fix = issue.get("fix", "")

            # Severity color
            sev_colors = {
                "critical": (248, 81, 73),
                "warning": (210, 153, 34),
                "info": (88, 166, 255),
            }
            r, g, b = sev_colors.get(severity, (139, 148, 158))

            # Issue header
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(r, g, b)
            pdf.cell(0, 7, f"#{i}  [{severity.upper()}] {issue_type.upper()} - Line {line}", new_x="LMARGIN", new_y="NEXT")

            # Description
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(225, 228, 232)
            w = pdf.w - pdf.l_margin - pdf.r_margin
            pdf.multi_cell(w, 5, f"Issue: {desc}")

            # Fix
            pdf.set_text_color(63, 185, 80)
            pdf.multi_cell(w, 5, f"Fix: {fix}")
            pdf.ln(3)

            # Page break check
            if pdf.get_y() > 260:
                pdf.add_page()
    else:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(63, 185, 80)
        pdf.cell(0, 10, "No issues found - code looks clean!", new_x="LMARGIN", new_y="NEXT")

    # --- Explanation ---
    explanation = result.get("explanation", "")
    if explanation and explanation != "No issues found — code looks clean!":
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(88, 166, 255)
        pdf.cell(0, 10, "Fix Summary", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(225, 228, 232)
        w = pdf.w - pdf.l_margin - pdf.r_margin
        pdf.multi_cell(w, 6, explanation)
        pdf.ln(5)

    # --- Fixed Code ---
    fixed_code = result.get("fixed_code", "")
    if fixed_code and issues:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(88, 166, 255)
        pdf.cell(0, 10, "Fixed Code", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        pdf.set_font("Courier", "", 8)
        pdf.set_text_color(225, 228, 232)
        pdf.set_fill_color(13, 17, 23)

        for line_num, line in enumerate(fixed_code.split("\n"), 1):
            # Truncate long lines
            display_line = f"{line_num:4d} | {line}"
            if len(display_line) > 120:
                display_line = display_line[:117] + "..."
            # Replace characters that fpdf can't encode
            display_line = display_line.encode("latin-1", errors="replace").decode("latin-1")
            pdf.cell(0, 4, display_line, new_x="LMARGIN", new_y="NEXT", fill=True)

            if pdf.get_y() > 275:
                pdf.add_page()

    return pdf.output()
